"""add_lab_visit_count

Revision ID: ddda9e89a3af
Revises: 732fc3ca015e
Create Date: 2026-06-06 13:25:45.832681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddda9e89a3af'
down_revision: Union[str, Sequence[str], None] = '732fc3ca015e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('team_members', 'joined_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_unique_constraint(None, 'team_members', ['team_id', 'user_id'])
    op.alter_column('teams', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('test_cases', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_cases', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.alter_column('test_cases', 'steps',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test_cases', 'expected_result',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test_cases', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('test_cases', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('test_cases', 'folder',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('test_cases', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('test_cases', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('test_runs', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_runs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_runs', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('test_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('user_achievements', 'earned_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_unique_constraint(None, 'user_level_progress', ['user_id', 'level_id'])
    op.add_column('users', sa.Column('lab_visit_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lab_visit_count')
    op.drop_constraint(None, 'user_level_progress', type_='unique')
    op.alter_column('user_achievements', 'earned_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('test_runs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('test_runs', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('test_runs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_runs', 'test_case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_cases', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('test_cases', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('test_cases', 'folder',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('test_cases', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('test_cases', 'priority',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('test_cases', 'expected_result',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test_cases', 'steps',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test_cases', 'title',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.alter_column('test_cases', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(None, 'team_members', type_='unique')
    op.alter_column('team_members', 'joined_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('team_members', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
